const path = require('path'),
    config = {};

// API settings
config.api = {
    sessionDuration: 3600, // in seconds,
    salt: '$2a$10$ZzU7rZOTPSagDgR9ltdeHO', // salt generated by bcrypt,
    appRoot: path.resolve(__dirname) + '/',
    avatarRoute: '/avatar/',
    paginationItems: 10 // Default value for requested items
};

// Logs directory
config.api.logsDir = path.join(config.api.appRoot, 'logs/');

// File upload paths
config.api.uploadDir = {};
config.api.uploadDir.main = path.join(config.api.appRoot, 'uploads/');
config.api.uploadDir.avatars = path.join(config.api.uploadDir.main, 'avatars/');

// Server configuration
config.server = {
    host: '',
    port: 3000
};

// Database configuration
config.database = {
    host: 'localhost',
    user: 'root',
    password: 'root',
    database: 'donart'
};
// config.database = {
//     host: 'wyqk6x041tfxg39e.chr7pe7iynqr.eu-west-1.rds.amazonaws.com',
//     user: 'qhdku9ijnr5wh69x',
//     password: 'kbq0bmk9fdj6t1db',
//     database: 'm0tj889wu2exupdm'
// };

// Authentication protected endpoints
config.protectedEndpoints = [
    '/users/save',
    '/users/deleteUser',
    '/services/saveCategory',
    '/services/deleteCategory',
    '/services/saveService',
    '/services/deleteService',
    '/services/getAll',
    '/clients/save',
    '/clients/addAddress',
    '/clients/deleteAddress',
    '/clients/filter',
    
];

module.exports = config;