const path = require('path'),
    config = {};

// API settings
config.api = {
    sessionDuration: 3600, // in seconds,
    salt: '$2a$10$ZzU7rZOTPSagDgR9ltdeHO', // salt generated by bcrypt,
    appRoot: path.resolve(__dirname) + '/',
    avatarRoute: '/avatar/',
    paginationItems: 10, // Default value for requested items
    siteOrder: {
        //TODO: Store in database
        workingTime: {
            workDays: {
                open: 8,
                closed: 19,
            },
            saturday: {
                open: 8,
                closed: 15
            },
        },
        diapason: 1, // Hours
        maxPickDateDays: 30, // The roof day is 30 days after today
        ordersPerDiapason: 3
    }
};

// Logs directory
config.api.logsDir = path.join(config.api.appRoot, 'logs/');

// File upload paths
config.api.uploadDir = {};
config.api.uploadDir.main = path.join(config.api.appRoot, 'uploads/');
config.api.uploadDir.avatars = path.join(config.api.uploadDir.main, 'avatars/');

// Server configuration
config.server = {
    host: '',
    port: 3000
};

// Database configuration
// config.database = {
//     host: 'localhost',
//     user: 'root',
//     password: 'root',
//     database: 'donart'
// };
config.database = {
    host: 'wyqk6x041tfxg39e.chr7pe7iynqr.eu-west-1.rds.amazonaws.com',
    user: 'qhdku9ijnr5wh69x',
    password: 'kbq0bmk9fdj6t1db',
    database: 'm0tj889wu2exupdm'
};

// Authentication protected endpoints
config.protectedEndpoints = [
    '/users/save',
    '/users/toggleActiveState',

    '/services/saveCategory',
    '/services/saveService',
    '/services/toggleActiveServiceState',
    '/services/toggleActiveServiceCategoryState',
    '/services/getAll',
    
    '/clients/save',
    '/clients/addAddress',
    '/clients/deleteAddress',
    '/clients/filter',
    
    '/configuration/save',
    '/configuration/delete',

    '/site/getOrders',
    '/site/createOrder',
    '/site/changeOrderStatus',
    '/site/getAvailableHours',

    '/orders/createOrder'
];

// Regex patterns
config.regex = {
    phone: /^\+?(?:[\d\s()]*)$/,
    email: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
};

config.mailgun = {
    inboxInfo: "info@donart.bg, anton.a.dimitrov@gmail.com",
    inboxOrders: "orders@donart.bg, anton.a.dimitrov@gmail.com",
    domain: "www.donart.bg",
    apiKey: "key-2fa8e0942e94b0bdef0c46343620e20b"
}

module.exports = config;