const path = require('path'),
    config = {};

// API settings
config.api = {
    sessionDuration: 3600, // in seconds,
    salt: '$2a$10$ZzU7rZOTPSagDgR9ltdeHO', // salt generated by bcrypt,
    appRoot: path.resolve(__dirname) + '/',
    avatarRoute: '/avatar/',
    paginationItems: 10, // Default value for requested items
    siteOrder: {
        //TODO: Store in database
        workingTime: {
            workDays: {
                from: 8,
                to: 21,
            },
            saturday: {
                from: 9,
                to: 16
            },
        },
        diapason: 3600, // 1 hour in seconds
        maxPickDateDays: 30, // The roof day is 30 days after today
    }
};

// Logs directory
config.api.logsDir = path.join(config.api.appRoot, 'logs/');

// File upload paths
config.api.uploadDir = {};
config.api.uploadDir.main = path.join(config.api.appRoot, 'uploads/');
config.api.uploadDir.avatars = path.join(config.api.uploadDir.main, 'avatars/');
config.api.uploadDir.defaultAvatar = path.join(config.api.uploadDir.avatars, 'default.png');

// Server configuration
config.server = {
    host: '',
    port: 3000
};

// Database configuration
config.database = {
    host: '',
    user: '',
    password: '',
    database: ''
};

// Authentication protected endpoints
config.protectedEndpoints = [
    '/users/save',
    '/users/toggleActiveState',

    '/services/saveCategory',
    '/services/saveService',
    '/services/toggleActiveServiceState',
    '/services/toggleActiveServiceCategoryState',
    '/services/getAll',
    
    '/clients/save',
    '/clients/addAddress',
    '/clients/deleteAddress',
    '/clients/filter',
    
    '/configuration/save',
    '/configuration/delete',

    '/site/getOrders',
    '/site/createOrder',
    '/site/changeOrderStatus',
    '/site/getAvailableHours',
];

// Regex patterns
config.regex = {
    phone: /^\+?(?:[\d\s()]*)$/,
    email: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
};

config.mailgun = {
    // inbox: "anton.a.dimitrov@gmail.com",
    inbox: "g.georgiev.work@gmail.com",
    domain: "www.donart.bg",
    apiKey: "key-2fa8e0942e94b0bdef0c46343620e20b"
}

module.exports = config;